"""empty message

Revision ID: 104150ad9cb5
Revises: None
Create Date: 2015-08-27 20:42:58.882561

"""

# revision identifiers, used by Alembic.
revision = '104150ad9cb5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('chart_config_json', sa.Text(), nullable=True))
    op.add_column('record', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('url_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'record', ['url_id'])
    op.create_foreign_key(None, 'record', 'record', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_constraint(None, 'record', type_='unique')
    op.drop_column('record', 'url_id')
    op.drop_column('record', 'parent_id')
    op.drop_column('record', 'chart_config_json')
    ### end Alembic commands ###
